title: الجمعية السعودية للمعلوماتية الحيوية
description: جمعية رسمية مسجلة في الهيئة السعودية للتخصصات الصحية ومقرها المملكة العربية السعودية
show_downloads: true

button_joinus_url: joinus
google_analytics:
theme: jekyll-theme-cayman